### ISSUE TITLE
Unable to install concerto_content_scheduling plugin in Concerto 2.3.3

### ISSUE THREAD

**Issue by robp2175** [concerto-addons/concerto_content_scheduling#26]
When trying to install the plugin in Conerto 2.3.3 I am getting this error

```
Bundler error: Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 4.2.5.1)

  In Gemfile:
    rails (~> 4.2.5)

    concerto_content_scheduling was resolved to 0.0.1, which depends on
      rails (~> 3.2.9)

    concerto_emergency was resolved to 0.9, which depends on
      rails (>= 3.2.9)

    concerto_shib_auth was resolved to 0.0.6, which depends on
      concerto_identity was resolved to 0.0.5, which depends on
        rails (>= 3.0)

    concerto_shib_auth was resolved to 0.0.6, which depends on
      rails



Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
 (RuntimeError)
  /usr/share/concerto/config/boot.rb:67:in `<top (required)>'
  /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/share/concerto/config/setup_load_paths.rb:7:in `<top (required)>'
  /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:232:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'

Error ID
    16a65c52
Application root
    /usr/share/concerto
```

**Comment by mfrederickson** [comment]
@robp2175 did you get this resolved?  It looks to me like there are some other gems requiring earlier versions of rails.  I was able to install this plugin through the gui on 2.3.3 just fine-- though I did have to recompile the assets.

**Comment by mfrederickson** [comment]
@robp2175 closing this.  If you need further help, please reopen.  Thanks.
